### ISSUE TITLE
cannot import name search error in kali linux

### ISSUE THREAD

**Issue by RackoS** [joe-shenouda/awesome-cyber-skills#13]
I downloaded Trity and ı ınstalled it but it is not working. I tried a few program and ı try kali linux in virtualbox but it is not working 
only working on parrot os 

the first time error is "no module named google"
I fix that but this time there is this error

PLS Help Me 

https://user-images.githubusercontent.com/35405544/34909068-7b228bd8-f8a3-11e7-83a3-a1cbff4f1838.png

sorry for my english

**Comment by sangam981020** [comment]
Ma face book account is block help me
