### ISSUE TITLE
dareyourmind.net is now a porn site

### ISSUE THREAD

**Issue by VeerD** [joe-shenouda/awesome-cyber-skills#16]
http://www.dareyourmind.net/ = this now takes you to a porn site

See the [last snapshot in 2018](https://web.archive.org/web/20180625201157/http://www.dareyourmind.net/index.html), which contains the following message:
```
After a fatal HDD crash, Dareyourmind.net died on 2017, July !
Sorry for that !

totoiste (totoiste at gmail dot com)
```

Please add a large warning and change the link to an older version: https://web.archive.org/web/20170618221231/http://www.dareyourmind.net/

**Comment by joe-shenouda** [comment]
Thank you @VeerD for finding this change of topic on that website :) I've updated the link accordingly.
